SELECT SUM(CASE WHEN location LIKE '%Afghanistan%' THEN 1 ELSE 0 END) AS "AFG",            
    SUM(CASE WHEN location LIKE '%Angola%' THEN 1 ELSE 0 END) AS "AGO",
    SUM(CASE WHEN location LIKE '%Albania%' THEN 1 ELSE 0 END) AS "ALB",
    SUM(CASE WHEN location LIKE '%Arab%' THEN 1 ELSE 0 END) AS "ARE",
    SUM(CASE WHEN location LIKE '%Argentina%' THEN 1 ELSE 0 END) AS "ARG",
    SUM(CASE WHEN location LIKE '%Armenia%' THEN 1 ELSE 0 END) AS "ARM",
    SUM(CASE WHEN location LIKE '%Antarctica%' THEN 1 ELSE 0 END) AS "ATA",
    SUM(CASE WHEN location LIKE '%Antarctic%' THEN 1 ELSE 0 END) AS "ATF",
    SUM(CASE WHEN location LIKE '%Australia%' THEN 1 ELSE 0 END) AS "AUS",
    SUM(CASE WHEN location LIKE '%Austria%' THEN 1 ELSE 0 END) AS "AUT",
    SUM(CASE WHEN location LIKE '%Azerbaijan%' THEN 1 ELSE 0 END) AS "AZE",
    SUM(CASE WHEN location LIKE '%Burundi%' THEN 1 ELSE 0 END) AS "BDI",
    SUM(CASE WHEN location LIKE '%Belgium%' THEN 1 ELSE 0 END) AS "BEL",
    SUM(CASE WHEN location LIKE '%Benin%' THEN 1 ELSE 0 END) AS "BEN",
    SUM(CASE WHEN location LIKE '%Burkina Faso%' THEN 1 ELSE 0 END) AS "BFA",
    SUM(CASE WHEN location LIKE '%Bangladesh%' THEN 1 ELSE 0 END) AS "BGD",
    SUM(CASE WHEN location LIKE '%Bulgaria%' THEN 1 ELSE 0 END) AS "BGR",
    SUM(CASE WHEN location LIKE '%The Bahamas%' THEN 1 ELSE 0 END) AS "BHS",
    SUM(CASE WHEN location LIKE '%Bosnia Herzegovina%' THEN 1 ELSE 0 END) AS "BIH",
    SUM(CASE WHEN location LIKE '%Belarus%' THEN 1 ELSE 0 END) AS "BLR",
    SUM(CASE WHEN location LIKE '%Belize%' THEN 1 ELSE 0 END) AS "BLZ",
    SUM(CASE WHEN location LIKE '%Bolivia%' THEN 1 ELSE 0 END) AS "BOL",
    SUM(CASE WHEN location LIKE '%Brazil%' THEN 1 ELSE 0 END) AS "BRA",
    SUM(CASE WHEN location LIKE '%Brunei%' THEN 1 ELSE 0 END) AS "BRN",
    SUM(CASE WHEN location LIKE '%Bhutan%' THEN 1 ELSE 0 END) AS "BTN",
    SUM(CASE WHEN location LIKE '%Botswana%' THEN 1 ELSE 0 END) AS "BWA",
    SUM(CASE WHEN location LIKE '%African Republic%' THEN 1 ELSE 0 END) AS "CAF",
    SUM(CASE WHEN location LIKE '%Canada%' THEN 1 ELSE 0 END) AS "CAN",
    SUM(CASE WHEN location LIKE '%Switzerland%' THEN 1 ELSE 0 END) AS "CHE",
    SUM(CASE WHEN location LIKE '%Chile%' THEN 1 ELSE 0 END) AS "CHL",
    SUM(CASE WHEN location LIKE '%China%' THEN 1 ELSE 0 END) AS "CHN",
    SUM(CASE WHEN location LIKE '%Ivory Coast%' THEN 1 ELSE 0 END) AS "CIV",
    SUM(CASE WHEN location LIKE '%Cameroon%' THEN 1 ELSE 0 END) AS "CMR",
    SUM(CASE WHEN location LIKE '%Democratic Republic of the Congo%' THEN 1 ELSE 0 END) AS "COD",
    SUM(CASE WHEN location LIKE '%Republic of the Congo%' THEN 1 ELSE 0 END) AS "COG",
    SUM(CASE WHEN location LIKE '%Colombia%' THEN 1 ELSE 0 END) AS "COL",
    SUM(CASE WHEN location LIKE '%Costa Rica%' THEN 1 ELSE 0 END) AS "CRI",
    SUM(CASE WHEN location LIKE '%Cuba%' THEN 1 ELSE 0 END) AS "CUB",
    SUM(CASE WHEN location LIKE '%Cyprus%' THEN 1 ELSE 0 END) AS "CYP",
    SUM(CASE WHEN location LIKE '%Czech Republic%' THEN 1 ELSE 0 END) AS "CZE",
    SUM(CASE WHEN location LIKE '%Germany%' THEN 1 ELSE 0 END) AS "DEU",
    SUM(CASE WHEN location LIKE '%Djibouti%' THEN 1 ELSE 0 END) AS "DJI",
    SUM(CASE WHEN location LIKE '%Denmark%' THEN 1 ELSE 0 END) AS "DNK",
    SUM(CASE WHEN location LIKE '%Dominican%' THEN 1 ELSE 0 END) AS "DOM",
    SUM(CASE WHEN location LIKE '%Algeria%' THEN 1 ELSE 0 END) AS "DZA",
    SUM(CASE WHEN location LIKE '%Ecuador%' THEN 1 ELSE 0 END) AS "ECU",
    SUM(CASE WHEN location LIKE '%Egypt%' THEN 1 ELSE 0 END) AS "EGY",
    SUM(CASE WHEN location LIKE '%Eritrea%' THEN 1 ELSE 0 END) AS "ERI",
    SUM(CASE WHEN location LIKE '%Spain%' THEN 1 ELSE 0 END) AS "ESP",
    SUM(CASE WHEN location LIKE '%Estonia%' THEN 1 ELSE 0 END) AS "EST",
    SUM(CASE WHEN location LIKE '%Ethiopia%' THEN 1 ELSE 0 END) AS "ETH",
    SUM(CASE WHEN location LIKE '%Finland%' THEN 1 ELSE 0 END) AS "FIN",
    SUM(CASE WHEN location LIKE '%Fiji%' THEN 1 ELSE 0 END) AS "FJI",
    SUM(CASE WHEN location LIKE '%Falkland Islands%' THEN 1 ELSE 0 END) AS "FLK",
    SUM(CASE WHEN location LIKE '%France%' THEN 1 ELSE 0 END) AS "FRA",
    SUM(CASE WHEN location LIKE '%Gabon%' THEN 1 ELSE 0 END) AS "GAB",
    SUM(CASE WHEN location LIKE '%UK%' THEN 1 ELSE 0 END) AS "GBR",
    SUM(CASE WHEN location LIKE '%Georgia%' THEN 1 ELSE 0 END) AS "GEO",
    SUM(CASE WHEN location LIKE '%Ghana%' THEN 1 ELSE 0 END) AS "GHA",
    SUM(CASE WHEN location LIKE '%Guinea%' THEN 1 ELSE 0 END) AS "GIN",
    SUM(CASE WHEN location LIKE '%Gambia%' THEN 1 ELSE 0 END) AS "GMB",
    SUM(CASE WHEN location LIKE '%Guinea%' THEN 1 ELSE 0 END) AS "GNB",
    SUM(CASE WHEN location LIKE '%Equatorial Guinea%' THEN 1 ELSE 0 END) AS "GNQ",
    SUM(CASE WHEN location LIKE '%Greece%' THEN 1 ELSE 0 END) AS "GRC",
    SUM(CASE WHEN location LIKE '%Greenland%' THEN 1 ELSE 0 END) AS "GRL",
    SUM(CASE WHEN location LIKE '%Guatemala%' THEN 1 ELSE 0 END) AS "GTM",
    SUM(CASE WHEN location LIKE '%Guyana%' THEN 1 ELSE 0 END) AS "GUY",
    SUM(CASE WHEN location LIKE '%Honduras%' THEN 1 ELSE 0 END) AS "HND",
    SUM(CASE WHEN location LIKE '%Croatia%' THEN 1 ELSE 0 END) AS "HRV",
    SUM(CASE WHEN location LIKE '%Haiti%' THEN 1 ELSE 0 END) AS "HTI",
    SUM(CASE WHEN location LIKE '%Hungary%' THEN 1 ELSE 0 END) AS "HUN",
    SUM(CASE WHEN location LIKE '%Indonesia%' THEN 1 ELSE 0 END) AS "IDN",
    SUM(CASE WHEN location LIKE '%India%' THEN 1 ELSE 0 END) AS "IND",
    SUM(CASE WHEN location LIKE '%Ireland%' THEN 1 ELSE 0 END) AS "IRL",
    SUM(CASE WHEN location LIKE '%Iran%' THEN 1 ELSE 0 END) AS "IRN",
    SUM(CASE WHEN location LIKE '%Iraq%' THEN 1 ELSE 0 END) AS "IRQ",
    SUM(CASE WHEN location LIKE '%Iceland%' THEN 1 ELSE 0 END) AS "ISL",
    SUM(CASE WHEN location LIKE '%Israel%' THEN 1 ELSE 0 END) AS "ISR",
    SUM(CASE WHEN location LIKE '%Italy%' THEN 1 ELSE 0 END) AS "ITA",
    SUM(CASE WHEN location LIKE '%Jamaica%' THEN 1 ELSE 0 END) AS "JAM",
    SUM(CASE WHEN location LIKE '%Jordan%' THEN 1 ELSE 0 END) AS "JOR",
    SUM(CASE WHEN location LIKE '%Japan%' THEN 1 ELSE 0 END) AS "JPN",
    SUM(CASE WHEN location LIKE '%Kazakhstan%' THEN 1 ELSE 0 END) AS "KAZ",
    SUM(CASE WHEN location LIKE '%Kenya%' THEN 1 ELSE 0 END) AS "KEN",
    SUM(CASE WHEN location LIKE '%Kyrgyzstan%' THEN 1 ELSE 0 END) AS "KGZ",
    SUM(CASE WHEN location LIKE '%Cambodia%' THEN 1 ELSE 0 END) AS "KHM",
    SUM(CASE WHEN location LIKE '%Kosovo%' THEN 1 ELSE 0 END) AS "OSA",
    SUM(CASE WHEN location LIKE '%Kuwait%' THEN 1 ELSE 0 END) AS "KWT",
    SUM(CASE WHEN location LIKE '%Laos%' THEN 1 ELSE 0 END) AS "LAO",
    SUM(CASE WHEN location LIKE '%Lebanon%' THEN 1 ELSE 0 END) AS "LBN",
    SUM(CASE WHEN location LIKE '%Liberia%' THEN 1 ELSE 0 END) AS "LBR",
    SUM(CASE WHEN location LIKE '%Libya%' THEN 1 ELSE 0 END) AS "LBY",
    SUM(CASE WHEN location LIKE '%Sri Lanka%' THEN 1 ELSE 0 END) AS "LKA",
    SUM(CASE WHEN location LIKE '%Lesotho%' THEN 1 ELSE 0 END) AS "LSO",
    SUM(CASE WHEN location LIKE '%Lithuania%' THEN 1 ELSE 0 END) AS "LTU",
    SUM(CASE WHEN location LIKE '%Luxembourg%' THEN 1 ELSE 0 END) AS "LUX",
    SUM(CASE WHEN location LIKE '%Latvia%' THEN 1 ELSE 0 END) AS "LVA",
    SUM(CASE WHEN location LIKE '%Morocco%' THEN 1 ELSE 0 END) AS "MAR",
    SUM(CASE WHEN location LIKE '%Moldova%' THEN 1 ELSE 0 END) AS "MDA",
    SUM(CASE WHEN location LIKE '%Madagascar%' THEN 1 ELSE 0 END) AS "MDG",
    SUM(CASE WHEN location LIKE '%Mexico%' THEN 1 ELSE 0 END) AS "MEX",
    SUM(CASE WHEN location LIKE '%Macedonia%' THEN 1 ELSE 0 END) AS "MKD",
    SUM(CASE WHEN location LIKE '%Mali%' THEN 1 ELSE 0 END) AS "MLI",
    SUM(CASE WHEN location LIKE '%Myanmar%' THEN 1 ELSE 0 END) AS "MMR",
    SUM(CASE WHEN location LIKE '%Montenegro%' THEN 1 ELSE 0 END) AS "MNE",
    SUM(CASE WHEN location LIKE '%Mongolia%' THEN 1 ELSE 0 END) AS "MNG",
    SUM(CASE WHEN location LIKE '%Mozambique%' THEN 1 ELSE 0 END) AS "MOZ",
    SUM(CASE WHEN location LIKE '%Mauritania%' THEN 1 ELSE 0 END) AS "MRT",
    SUM(CASE WHEN location LIKE '%Malawi%' THEN 1 ELSE 0 END) AS "MWI",
    SUM(CASE WHEN location LIKE '%Malaysia%' THEN 1 ELSE 0 END) AS "MYS",
    SUM(CASE WHEN location LIKE '%Namibia%' THEN 1 ELSE 0 END) AS "NAM",
    SUM(CASE WHEN location LIKE '%Caledonia%' THEN 1 ELSE 0 END) AS "NCL",
    SUM(CASE WHEN location LIKE '%Niger%' THEN 1 ELSE 0 END) AS "NER",
    SUM(CASE WHEN location LIKE '%Nigeria%' THEN 1 ELSE 0 END) AS "NGA",
    SUM(CASE WHEN location LIKE '%Nicaragua%' THEN 1 ELSE 0 END) AS "NIC",
    SUM(CASE WHEN location LIKE '%Netherlands%' THEN 1 ELSE 0 END) AS "NLD",
    SUM(CASE WHEN location LIKE '%Norway%' THEN 1 ELSE 0 END) AS "NOR",
    SUM(CASE WHEN location LIKE '%Nepal%' THEN 1 ELSE 0 END) AS "NPL",
    SUM(CASE WHEN location LIKE '%New Zealand%' THEN 1 ELSE 0 END) AS "NZL",
    SUM(CASE WHEN location LIKE '%Oman%' THEN 1 ELSE 0 END) AS "OMN",
    SUM(CASE WHEN location LIKE '%Pakistan%' THEN 1 ELSE 0 END) AS "PAK",
    SUM(CASE WHEN location LIKE '%Panama%' THEN 1 ELSE 0 END) AS "PAN",
    SUM(CASE WHEN location LIKE '%Peru%' THEN 1 ELSE 0 END) AS "PER",
    SUM(CASE WHEN location LIKE '%Philippines%' THEN 1 ELSE 0 END) AS "PHL",
    SUM(CASE WHEN location LIKE '%Papua New Guinea%' THEN 1 ELSE 0 END) AS "PNG",
    SUM(CASE WHEN location LIKE '%Poland%' THEN 1 ELSE 0 END) AS "POL",
    SUM(CASE WHEN location LIKE '%Puerto Rico%' THEN 1 ELSE 0 END) AS "PRI",
    SUM(CASE WHEN location LIKE '%Portugal%' THEN 1 ELSE 0 END) AS "PRT",
    SUM(CASE WHEN location LIKE '%Paraguay%' THEN 1 ELSE 0 END) AS "PRY",
    SUM(CASE WHEN location LIKE '%Qatar%' THEN 1 ELSE 0 END) AS "QAT",
    SUM(CASE WHEN location LIKE '%Romania%' THEN 1 ELSE 0 END) AS "ROU",
    SUM(CASE WHEN location LIKE '%Russia%' THEN 1 ELSE 0 END) AS "RUS",
    SUM(CASE WHEN location LIKE '%Rwanda%' THEN 1 ELSE 0 END) AS "RWA",
    SUM(CASE WHEN location LIKE '%Western Sahara%' THEN 1 ELSE 0 END) AS "ESH",
    SUM(CASE WHEN location LIKE '%Saudi Arabia%' THEN 1 ELSE 0 END) AS "SAU",
    SUM(CASE WHEN location LIKE '%Sudan%' THEN 1 ELSE 0 END) AS "SDN",
    SUM(CASE WHEN location LIKE '%South Sudan%' THEN 1 ELSE 0 END) AS "SDS",
    SUM(CASE WHEN location LIKE '%Senegal%' THEN 1 ELSE 0 END) AS "SEN",
    SUM(CASE WHEN location LIKE '%Solomon Islands%' THEN 1 ELSE 0 END) AS "SLB",
    SUM(CASE WHEN location LIKE '%Sierra Leone%' THEN 1 ELSE 0 END) AS "SLE",
    SUM(CASE WHEN location LIKE '%El Salvador%' THEN 1 ELSE 0 END) AS "SLV",
    SUM(CASE WHEN location LIKE '%Somaliland%' THEN 1 ELSE 0 END) AS "ABV",
    SUM(CASE WHEN location LIKE '%Somalia%' THEN 1 ELSE 0 END) AS "SOM",
    SUM(CASE WHEN location LIKE '%Serbia%' THEN 1 ELSE 0 END) AS "SRB",
    SUM(CASE WHEN location LIKE '%Suriname%' THEN 1 ELSE 0 END) AS "SUR",
    SUM(CASE WHEN location LIKE '%Slovakia%' THEN 1 ELSE 0 END) AS "SVK",
    SUM(CASE WHEN location LIKE '%Slovenia%' THEN 1 ELSE 0 END) AS "SVN",
    SUM(CASE WHEN location LIKE '%Sweden%' THEN 1 ELSE 0 END) AS "SWE",
    SUM(CASE WHEN location LIKE '%Swaziland%' THEN 1 ELSE 0 END) AS "SWZ",
    SUM(CASE WHEN location LIKE '%Syria%' THEN 1 ELSE 0 END) AS "SYR",
    SUM(CASE WHEN location LIKE '%Chad%' THEN 1 ELSE 0 END) AS "TCD",
    SUM(CASE WHEN location LIKE '%Togo%' THEN 1 ELSE 0 END) AS "TGO",
    SUM(CASE WHEN location LIKE '%Thailand%' THEN 1 ELSE 0 END) AS "THA",
    SUM(CASE WHEN location LIKE '%Tajikistan%' THEN 1 ELSE 0 END) AS "TJK",
    SUM(CASE WHEN location LIKE '%Turkmenistan%' THEN 1 ELSE 0 END) AS "TKM",
    SUM(CASE WHEN location LIKE '%East Timor%' THEN 1 ELSE 0 END) AS "TLS",
    SUM(CASE WHEN location LIKE '%Trinidad and Tobago%' THEN 1 ELSE 0 END) AS "TTO",
    SUM(CASE WHEN location LIKE '%Tunisia%' THEN 1 ELSE 0 END) AS "TUN",
    SUM(CASE WHEN location LIKE '%Turkey%' THEN 1 ELSE 0 END) AS "TUR",
    SUM(CASE WHEN location LIKE '%Taiwan%' THEN 1 ELSE 0 END) AS "TWN",
    SUM(CASE WHEN location LIKE '%Tanzania%' THEN 1 ELSE 0 END) AS "TZA",
    SUM(CASE WHEN location LIKE '%Uganda%' THEN 1 ELSE 0 END) AS "UGA",
    SUM(CASE WHEN location LIKE '%Ukraine%' THEN 1 ELSE 0 END) AS "UKR",
    SUM(CASE WHEN location LIKE '%Uruguay%' THEN 1 ELSE 0 END) AS "URY",
    SUM(CASE WHEN location LIKE '%USA%' THEN 1 ELSE 0 END) AS "USA",
    SUM(CASE WHEN location LIKE '%Uzbekistan%' THEN 1 ELSE 0 END) AS "UZB",
    SUM(CASE WHEN location LIKE '%Venezuela%' THEN 1 ELSE 0 END) AS "VEN",
    SUM(CASE WHEN location LIKE '%Vietnam%' THEN 1 ELSE 0 END) AS "VNM",
    SUM(CASE WHEN location LIKE '%Vanuatu%' THEN 1 ELSE 0 END) AS "VUT",
    SUM(CASE WHEN location LIKE '%West Bank%' THEN 1 ELSE 0 END) AS "PSE",
    SUM(CASE WHEN location LIKE '%Yemen%' THEN 1 ELSE 0 END) AS "YEM",
    SUM(CASE WHEN location LIKE '%South Africa%' THEN 1 ELSE 0 END) AS "ZAF",
    SUM(CASE WHEN location LIKE '%Zambia%' THEN 1 ELSE 0 END) AS "ZMB",
    SUM(CASE WHEN location LIKE '%Zimbabwe%' THEN 1 ELSE 0 END) AS "ZWE",
    SUM(CASE WHEN location LIKE '%Korea%' THEN 1 ELSE 0 END) AS "KOR"

FROM earthquakes
WHERE time > '2024-01-01';